# Generated by Django 4.1.7 on 2023-03-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='gender',
            field=models.CharField(choices=[('женский', 'Женский'), ('мужской', 'Мужской'), ('средний', 'Средний')], max_length=7, verbose_name='Gender'),
        ),
    ]
